name: Build packages

on:
  pull_request:

jobs:
  build_all:
    name: Build all known packages
    runs-on: self-hosted
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install and update packages
        run: pacman --noconfirm -Syyu curl python python-pip sudo
      - name: Install needed packages
        run: pip install -r requirements.txt
      - name: Test building
        run: sudo -u nobody makepkg